.PHONY: test
test:
	perl part1.pl < part1-test1.txt
	perl part1.pl < part1-test2.txt
	perl part1.pl < part1-test3.txt
	perl part2.pl < part2-test1.txt
	perl part2.pl < part2-test2.txt
	perl part2.pl < part2-test3.txt
	perl part2.pl < part2-test4.txt

answers:
	perl part1.pl < input.txt
	perl part2.pl < input.txt
